version: '3.4'

name: event-player-dev
services:
  event-player-dev:
    image: cloudevent-player
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn api.app:app --host 0.0.0.0 --port 80 --reload"]
    ports:
      - 8885:80
      - 5675:5678
    environment:
      api_tag: "0.1.15"
      api_repository_url: "https://github.com/bvandewe/cloudevents-player"
      api_log_level: DEBUG
      api_log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      api_default_generator_gateways: '{"urls": ["http://localhost/events/pub", "http://event-player-dev/events/pub", "https://events-gateway.mydomain.com/events/pub", "https://webhook.site/bddfa626-2c77-4914-9c4a-68b4db99f9aa"]}'
      api_browser_queue_size: 1000
    volumes:
      - .:/app
